### ISSUE TITLE
reviewdog: failed to run 'git rev-parse --show-prefix': exit status 128

### ISSUE THREAD

**Issue by MariachiForHire** [reviewdog/action-tflint#21]
Hi - 

I'm getting error: reviewdog: failed to run 'git rev-parse --show-prefix': exit status 128. Can someone help out?

Here is my action.yaml 
```  
name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
     - name: Run tflint with reviewdog
       uses: reviewdog/action-tflint@master
       with:
        github_token: ${{ secrets.REVIEWDOGTOKEN}}
        level: warning # optional, default is error
        reporter: github-pr-check # optional, default is github-pr-check
        flags: --module # optional, default is --module
```
