### ISSUE TITLE
reviewdog: failed to run 'git rev-parse --show-prefix': exit status 128

### ISSUE THREAD

**Issue by denzhel** [reviewdog/action-tflint#22]
Hi there,

I have the same issue in this link:
https://github.com/reviewdog/action-tflint/issues/21

This is the setup I use
```
    steps:
    - uses: actions/checkout@v2
    - name: tflint
      uses: reviewdog/action-tflint@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review # Optional. Change reporter
        filter_mode: "nofilter" # Optional. Check all files, not just the diff
        flags: "--module" # Optional. Add custom tflint flags
```

and I still get:
```
reviewdog: failed to run 'git rev-parse --show-prefix': exit status 128
```

Please help :)
