### ISSUE TITLE
No way to pass flags to `tflint --init`

### ISSUE THREAD

**Issue by Sebelino** [reviewdog/action-tflint#57]
Use case: I have a repository with a single `.tflint.hcl` which contains the `terraform` and `aws` plugins. I'd like this file to be the single source of truth for how `tflint` is configured to run both locally and in CI.

I can almost achieve this by using the `flags` argument and passing `--config` to `tflint` directly:

```
- uses: reviewdog/action-tflint@v1.17.0
  with:
    tflint_init: true
    flags: --config=${{ github.workspace }}/terraform/.tflint.hcl
```

However, since the value of the `flags` argument is [never passed](https://github.com/reviewdog/action-tflint/blob/46e609666b039b775a150e84781ef79ea90089a8/script.sh#L76) to the `tflint --init` command, the plugins are never installed, resulting in the following error:

```
Running tflint with reviewdog 🐶 ...
  Failed to initialize plugins; Plugin `terraform` not found. Did you run `tflint --init`?
```
